title: Elemental Code's Blog
description: "A game development blog"
author:
  name: "Elemental Code (Milton Candelero)"
  email: "miltoncandelero@gmail.com"
  url: "https://twitter.com/MiltonCandelero"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Milton Candelero"
year : "2024"
