remote_theme: fongandrew/hydeout

title:            'Elemental Code'
tagline:          'A game development blog'
description:      'Let&#39;s solve problems by creating bigger problems!'

author:
  name:           'Milton Candelero'
  
paginate: 5

disqus:
  shortname: elemental-code

url:              https://miltoncandelero.github.io
#baseurl:          '/'

plugins:
  - jemoji